#!/usr/bin/env bash
# Fill packaging/aur/PKGBUILD with the release version and real sha256 sums.
# .SRCINFO is generated by the AUR deploy action inside its Arch container.
# Usage: update-aur.sh <version> <dist-dir>
set -euo pipefail

VERSION="${1:?version required}"
DIST="${2:?dist dir required}"
PKGBUILD="packaging/aur/PKGBUILD"

sha_for() {
  local target="$1"
  local file="${DIST}/skillsdash-${VERSION}-${target}.tar.gz.sha256"
  if [ ! -f "$file" ]; then
    echo "::error::missing checksum for ${target} (${file})" >&2
    exit 1
  fi
  awk '{print $1}' "$file"
}

X86="$(sha_for x86_64-unknown-linux-gnu)"
ARM="$(sha_for aarch64-unknown-linux-gnu)"

# Portable in-place edit (GNU sed on CI, BSD sed on macOS both work).
sed_i() {
  local expr="$1" file="$2"
  local tmp
  tmp="$(mktemp)"
  sed "$expr" "$file" > "$tmp"
  mv "$tmp" "$file"
}

sed_i "s/^pkgver=.*/pkgver=${VERSION}/" "$PKGBUILD"
sed_i "s/^pkgrel=.*/pkgrel=1/" "$PKGBUILD"
sed_i "s/^sha256sums_x86_64=.*/sha256sums_x86_64=('${X86}')/" "$PKGBUILD"
sed_i "s/^sha256sums_aarch64=.*/sha256sums_aarch64=('${ARM}')/" "$PKGBUILD"

echo "PKGBUILD updated to ${VERSION}"
echo "  x86_64:  ${X86}"
echo "  aarch64: ${ARM}"
